sudo: false

cache:
  directories:
    - .cabal-sandbox

language: haskell

ghc:
  - 7.8
  - 7.6
  - 7.4

before_install:
  - cabal install alex happy
  - cabal sandbox init
  - cabal sandbox hc-pkg dump
  - cabal install --enable-tests --dry-run -v2

install:
  - cabal install --enable-tests

script:
  - cabal test
